name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/haskell.yml
  release:
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      name: Download source distribution file artifact
      with:
        name: source-distribution-file
        path: ./artifacts
    - uses: actions/download-artifact@v3
      name: Download haddock artifact
      with:
        name: github-pages
        path: ./artifacts
    - name: Create release draft (GitHub)
      env:
        MAESTRO_API_VERSION: ${{needs.build.outputs.MAESTRO_API_VERSION}}
      run: |
        export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
        SEMANTIC_VERSION=v${MAESTRO_API_VERSION/#maestro-api-}
        TAGS=$(git describe --tags)
        GIT_REVISION=$(git rev-parse HEAD)
        CI_BUILD_TIME=$(date --iso-8601=seconds --utc)
        echo "MAESTRO_API_VERSION: ${{ env.MAESTRO_API_VERSION }}"
        echo "SEMANTIC_VERSION: $SEMANTIC_VERSION"
        echo "TAGS: $TAGS"
        echo "GIT_REVISION: $GIT_REVISION"
        echo "CI_BUILD_TIME: $CI_BUILD_TIME"
        HADDOCK_FILE=${{ env.MAESTRO_API_VERSION }}-haddock.tar
        set -x
        mv ./artifacts/artifact.tar ./artifacts/${HADDOCK_FILE}
        gh release create \
          --generate-notes \
          --verify-tag \
          --draft \
          "${SEMANTIC_VERSION}" \
          "./artifacts/${{ env.MAESTRO_API_VERSION }}.tar.gz#Source distribution file (tar.gz)" \
          "./artifacts/${HADDOCK_FILE}#Haddock (tar)"
        echo "::notice::Succesfully created release draft ${SEMANTIC_VERSION} from ${GIT_REVISION}. (Uploaded: ${{ env.MAESTRO_API_VERSION }}.tar.gz)"
          